name: check-compiles
on:
  push:
    branches: ["master"]
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.1.5"
          - "5.2.4"
          - "5.3.6"
          - "5.4.4"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: leafo/gh-actions-lua@v8
        with:
          luaVersion: ${{ matrix.luaVersion }}
      - uses: leafo/gh-actions-luarocks@v4
      - run: sudo apt-get install x11proto-dev libgl-dev libglx-dev libglu1-mesa-dev
      - run: luarocks make CFLAGS="-Wall -Wextra -O2 -fPIC"
      - run: lua -e 'print(require("tigr"))'

