name: check-compiles
on:
  push:
    branches: ["master"]
  pull_request:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4.4"
        osVersion:
          - "ubuntu-latest"
          - "windows-latest"
    runs-on: ${{ matrix.osVersion }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: ${{ matrix.luaVersion }}
          buildCache: false
      - uses: hishamhm/gh-actions-luarocks@master
      - run: sudo apt-get install x11proto-dev libgl-dev libglx-dev libglu1-mesa-dev
        if: ${{ matrix.osVersion == 'ubuntu-latest' }}
      - run: luarocks make
      - run: lua -e 'print(require("tigr"))'

